### ISSUE TITLE
Custom default values as input from templates

### ISSUE THREAD

**Issue by Eraldo** [divio/django-classy-tags#36]
Template `label.html`:

``` html
<span{%if class %} class="{{ class }}"{% endif %}>Label: {{ text }}</span>
```

What I currently use:

``` python
@register.simple_tag(takes_context=True)
def label(context, label=None, **kwargs):
    label = label or context.get('label', {})
    label_context = {
        'class': label.get('class'),
        'text': label.get('text', 'Default'),
    }
    label_context.update(kwargs)
    label_template = 'atoms/label.html'
    return render_to_string(label_template, context=label_context)
```

All of these inputs work:

``` html
{% label %}
=> <span>Label: Default</span>
{% label text="Dummy" %}
=> <span>Label: Dummy</span>
{% label text=name class="warning" %} // name="foo"
=> <span class="warning">Label: foo</span>
{% label text=name|default:'Anonymous'%} // name=None
=> <span>Label: Anonymous</span>
```

Features:
- Passing unlimited context variables to the tag.
- Using arbitrary django filters on input (example given: default value)

How can I get that with classy-tags?

I tried using this inclusin tag:

``` python
class Label(InclusionTag):
    template = 'atoms/label.html'
    options = Options(
        KeywordArgument('text'),
        KeywordArgument('class', required=False),
    )
    def get_context(self, context, **kwargs):
        return context.update(**kwargs)
register.tag(Label)
```

However that does not work yet.

With `{% label text='foo' %}`, kwargs becomes:
`{'class': {}, 'text': {'text': django.utils.safestring.SafeText('foo')}}`

Note: I do not want to force any order of arguments.

Any ideas?

**Comment by ojii** [comment]
You might want https://django-classy-tags.readthedocs.io/en/latest/arguments.html#multikeywordargument instead of two separate keyword arguments.

**Comment by Eraldo** [comment]
Nice @ojii. :)
That solves the multi issue.

One problem remains: django filters.

Input:
```
{% label text=name|default:'Anonymous' class=label_class|default:'label-pill bg-accent' %}
```
Error:
```
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: text|=name||default:'Anonymous'
```

**Comment by Eraldo** [comment]
@ojii Also is there something special going on.. even if I mark a string as "safe" in the `get_context` method.. I still get text instead of html output in my template.

Any ideas what is going on?

**Comment by ojii** [comment]
I'll have to look into this a bit deeper. I don't think filters will work at the moment (at least there's no tests for them).

If you're looking for a workaround, if you always have the same defaults, you can pass them to MultiKeywordArgument. As for the "safe", you could apply it in the included template.

For now, if you have the full traceback of the TemplateSyntaxError you got, that could be helpful.

**Comment by Eraldo** [comment]
Current version:
```python
@register.tag()
class Label(InclusionTag):
    template = 'atoms/label.html'

    options = Options(
        MultiKeywordArgument('kwargs', required=False),
    )

    def get_context(self, context, kwargs):
        context.update(kwargs)
        return context
```

This version does work in general.
However.. I am still trying to wrap my head around the 'safe' issue.
I cannot add the safe filter to the template because some kwargs are safe and others are not.
Adding it to the template would also render the user-supplied parts as safe which is a security concern.

If you now ask yourself why only some parts.. I intend to use them in a nested fashion:
Example:
```
ComplexTag(InclusionTag):
    template = 'atoms/complex.html'

    options = Options(
        MultiKeywordArgument('kwargs', required=False),
    )

    def get_context(self, context, kwargs):
        icon_data = kwargs.get('icon)
        icon = Icon().get_context(context, kwargs=icon_data)
        kwargs.update({'text': icon + kwargs.get('text')})
        context.update(kwargs)
        return context
```

That is a made up example.. I hope it makes sense. So, in that example.. the icon is safe and the text is not. Inside the complex template I would call label and its text keyword would include safe and unsafe contents (icon and text). Does that make sense to you?

**Comment by ojii** [comment]
The `|safe` issues are clear.

`Icon` in your example is another template tag?

Also what version of classy-tags, Django and Python are involved here?

**Comment by Eraldo** [comment]
Yes, `Icon` in this example would be another template tag.
```
Python 3.5.1
Django==1.9.1
django-classy-tags==0.7.2
```

**Comment by ojii** [comment]
But template tags take two arguments, how are you passing the parser and the tokens to it?

Also quick testing shows that filters (eg `|default`) do work in classy tags, so I'm not sure what the problem is. Can you come up with a minimal failing bit of code?

**Comment by Eraldo** [comment]
## Filters as input for tags
Just wanted to supply you with a failing bit of code.. and... I could not because it worked. ;)
I guess that was due to me mixing Argument and MultiKeywordArgument. In fact let my try that..
Yep.. that was it:
```python
@register.tag()
class Tag(InclusionTag):
    template = 'atoms/label.html'

    options = Options(
        Argument('text', required=False),
        MultiKeywordArgument('kwargs', required=False),
    )

    def get_context(self, context, kwargs):
        context.update(kwargs)
        return context
```
Call:
```html
{% tag text=missingvariable|default:"test" %}
```
Error:
```traceback
File "/Users/eraldo/.virtualenvs/colegend/lib/python3.5/site-packages/django/template/base.py", line 670, in __init__
token[start:]))
django.template.exceptions.TemplateSyntaxError: Could not parse some characters: text|=missingvariable||default:"test"
```

## Recursive use of tags
| But template tags take two arguments, how are you passing the parser and the tokens to it?
Oh.. that is true. Did not get that far.. was still stuck in concept land dealing with the safe question.

What I want is that any tag can be used as input to another tag.
So let me ask you: How do you recommend reusing template tags?

**Comment by ojii** [comment]
> I guess that was due to me mixing Argument and MultiKeywordArgument. In fact let my try that..
> Yep.. that was it:

Ah yes, since the first argument is not required, there's no way for classytags to know that you actually meant to supply the second one. Separate them with a "breakpoint":

```python
@register.tag()
class Tag(InclusionTag):
    template = 'atoms/label.html'

    options = Options(
        Argument('text', required=False),
        'breakpointname'
        MultiKeywordArgument('kwargs', required=False),
    )

    def get_context(self, context, kwargs):
        context.update(kwargs)
        return context
```

Which you can use like this:

```
{% tag textargument breakpointname foo='bar' %}
{% tag breakpointname foo='bar' %}
{% tag textargument %}
```

> What I want is that any tag can be used as input to another tag.
> So let me ask you: How do you recommend reusing template tags?

"As-Tags"

https://django-classy-tags.readthedocs.io/en/latest/usage.html#easy-as-tags

```
{% first_tag as output %}
{% second_tag output %}
```

**Comment by Eraldo** [comment]
I see - thank you.

Any ideas on how to deal with the `safe` issue?

**Comment by Eraldo** [comment]
My problem is that according to the django docs.. any string that I manually mark safe turns unsafe if that string is manipulated again. Meaning if I mark the return value of `get_context` with `mark_safe` it still ends up being unsafe because of what the class does with that context. That means I have no way to control what is and what is not safe if I want to avoid using the safe filter in the template.
Am I right?

**Comment by Eraldo** [comment]
Never mind.. it works now.. I used `format_html` instead of `string.format`. :)

**Comment by Eraldo** [comment]
@ojii can you please tell me how I can create an instance from a classy-tags class on the python side of things?

Example:
I want to create an instance of `Label`-class with the following given data: 
```python
kwargs = {'name': 'Test', 'class': 'small'}
```
Is there an easy intuitive way of doing that?

**Comment by Eraldo** [comment]
Currently I can use my templatetag-fuctions also in my views. I think the same fuctionality would also be great to have for class based tempalte tags.
