### ISSUE TITLE
Document AsTag implementation details

### ISSUE THREAD

**Issue by emorozov** [divio/django-classy-tags#41]
It is assumed in the `AsTag` implementation that the last argument of the tag is the variable name to save the result. But that assumption is not documented and leads to incorrect tag implementations.

For example, django-taggit-templatetags2 project implements its tags as a subclasses of the `AsTag` but they accept additional arguments after the `as varname` variable, and this leads to bugs that are very hard to understand and debug.

Perhaps, it should be explicitly noted in the documentation that the last argument of the `AsTag` is always assumed to be a context variable name.

**Comment by ojii** [comment]
Could you link me to the source where they allow extra arguments after the `as varname`? There's a check that should prevent that... https://github.com/ojii/django-classy-tags/blob/45d155cdd7cf8540e51b3b5e6c91a14b0e50afb3/classytags/helpers.py#L21-L25

**Comment by emorozov** [comment]
https://github.com/fizista/django-taggit-templatetags2/blob/master/taggit_templatetags2/templatetags/taggit_templatetags2_tags.py#L140

I didn't investigate yet how this happens and why this code doesn't fail early. It took me almost 2 hours just to find out what is causing this error, I have no more time today to figure out how it is possible or to fix the problem.

**Comment by ojii** [comment]
Well that passes the check because it has a breakpoint with exactly one argument at the end. Documenting how astag works is probably a good idea but it would be even better if it disallowed "wrong tags". Either by switching from "last argument" to "argument after as" or a special argument class to use for the target.

**Comment by ojii** [comment]
For reference https://github.com/fizista/django-taggit-templatetags2/issues/9
