### ISSUE TITLE
Django 3 issues - six is no longer availiable in django.utils

### ISSUE THREAD

**Issue by maddrum** [divio/django-classy-tags#48]
Hello!
"SIX" is not available in django.utils in Django 3, since all python 2 support is dropped.
So importing "SIX" in core.py throws exception.

**Comment by archatas** [comment]
Hello! What is the current roadmap for the upgrade? We need this for the django-sekizai to function on Django 3.0. Does the proposed pull request lack something? How can we help to push it forward?

**Comment by yakky** [comment]
Ping @FinalAngel : as soon as #50 is merged, we can make a release

**Comment by michael93pl** [comment]
Hello! How the situation looks like regarding the upcoming merge? Django-cookie-law uses django-classy-tags and the issue seems to be connected only with the six version. Is there something I can help with to speed the merge? Cheers!

**Comment by pallavg** [comment]
I am also experiencing issues witht his. Django-wiki has an dependency on django-classy-tags and I just hacked the source code to change `import django.util.six` -> `import six` to get it work. It will be great if #50 can be merged as and a release is made. Thank you.

**Comment by FinalAngel** [comment]
thanks for the feedback, I'm prepping to get Django 3 support across the supported addons and the CMS itself.

**Comment by archatas** [comment]
@FinalAngel Would it be possible to release a new version of django-classy-tags somewhen in the upcoming week, before doing the final updates of Django CMS?

**Comment by FinalAngel** [comment]
@archatas we potentially can merge the PR. Alternatively you can install classy-tags from Github temporarily. All depends a bit on testing and how fast I progress.

**Comment by yakky** [comment]
@FinalAngel I think it's worth to release classy-tags and sekizai very early in the django 3 migration process as they are enabler for a lot of third party apps that will allow them to catch up quicker with the django CMS releases
I can do this myself, if needed

**Comment by maddrum** [comment]
Is this project abandoned? It has been a month and no release has been made.

**Comment by FinalAngel** [comment]
@yakky yeah probably this week :)

**Comment by yakky** [comment]
:+1: let me know if you want me to handle it

**Comment by FinalAngel** [comment]
@yakky you are very welcome to merge and release as well!

**Comment by yakky** [comment]
> @yakky you are very welcome to merge and release as well!

I can merge but can't release (not added on PyPi)

**Comment by archatas** [comment]
@yakky Can you please at least merge the branches? It would be possible to use the installation directly from GitHub temporarily.

**Comment by yakky** [comment]
@FinalAngel I'd go with #50 (using six explicitly instead of #51 which uses a compat method) as it's more in line with what would be done in the other django cms apps

**Comment by FinalAngel** [comment]
👍

**Comment by yakky** [comment]
@FinalAngel I need an explicit review, otherwise I can't merge it due to repo settings :)
