### ISSUE TITLE
Distribute newest version on PyPi for Django 3 compatibilty

### ISSUE THREAD

**Issue by mpibpc-mroose** [divio/django-classy-tags#53]
Hi,
current PyPi version 0.9.0 is a bit behind the source here on Github.

Thus the PyPi package is **not Django 3 compliant** as it uses the deprecated import
``` 
# core.py
from django.utils import six
```
which has been already fixed in the sources.

**Suggestion:** make a fresh PyPi distibution.

**Comment by FinalAngel** [comment]
@mpibpc-mroose we have just released classy tags 1.0.0 with Django 3 compatibility :)
